name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: docker build . --file Dockerfile --tag ghcr.io/w1ndy/idg-kubectl:latest
    - name: push
      run: docker push ghcr.io/w1ndy/idg-kubectl:latest
